#!/bin/bash
set -x
PROJECT_ID=$1
DOCKER_USER_APPLICATION_NAME=$2
IMAGE_TAG=$3
APPLICATION_NAME=$4

export PROJECT_ID
export DOCKER_USER_APPLICATION_NAME
export IMAGE_TAG
export APPLICATION_NAME

gcloud config set project $PROJECT_ID
docker pull $DOCKER_USER_APPLICATION_NAME:$IMAGE_TAG
docker tag $DOCKER_USER_APPLICATION_NAME:$IMAGE_TAG gcr.io/$PROJECT_ID/$DOCKER_USER_APPLICATION_NAME:$IMAGE_TAG
docker push gcr.io/$PROJECT_ID/$DOCKER_USER_APPLICATION_NAME:$IMAGE_TAG
gcloud run deploy $APPLICATION_NAME --image=gcr.io/$PROJECT_ID/$DOCKER_USER_APPLICATION_NAME:$IMAGE_TAG --platform=managed --region=southamerica-east1 --allow-unauthenticated --revision-suffix=$IMAGE_TAG
docker rmi $DOCKER_USER_APPLICATION_NAME:$IMAGE_TAG
docker rmi gcr.io/$PROJECT_ID/$DOCKER_USER_APPLICATION_NAME:$IMAGE_TAG